
# DDG.shape: image
# DDG.icon: https://duckduckgo.com/assets/addons/logo.svg
# # {
# #   shape: image
# #   icon: 
# # }

PG: PostgreSQL
PG.shape: cylinder

User: user
User.shape: person

User <-> Query: REST
Query <-> DDG: HTTP Request
Query <-> Store: gRPC
Store <-> PG: GORM
