// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: pkg/duckduckgo/typespb/types.proto

package typespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Icon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int32  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	URL    string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Width  int32  `protobuf:"varint,3,opt,name=Width,proto3" json:"Width,omitempty"`
}

func (x *Icon) Reset() {
	*x = Icon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Icon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Icon) ProtoMessage() {}

func (x *Icon) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Icon.ProtoReflect.Descriptor instead.
func (*Icon) Descriptor() ([]byte, []int) {
	return file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP(), []int{0}
}

func (x *Icon) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Icon) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *Icon) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstURL string `protobuf:"bytes,1,opt,name=FirstURL,proto3" json:"FirstURL,omitempty"`
	Icon     *Icon  `protobuf:"bytes,2,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Result   string `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result,omitempty"`
	Text     string `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *Results) Reset() {
	*x = Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP(), []int{1}
}

func (x *Results) GetFirstURL() string {
	if x != nil {
		return x.FirstURL
	}
	return ""
}

func (x *Results) GetIcon() *Icon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Results) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Results) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type RelatedTopicsIcon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height string `protobuf:"bytes,1,opt,name=Height,proto3" json:"Height,omitempty"`
	URL    string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Width  string `protobuf:"bytes,3,opt,name=Width,proto3" json:"Width,omitempty"`
}

func (x *RelatedTopicsIcon) Reset() {
	*x = RelatedTopicsIcon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelatedTopicsIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedTopicsIcon) ProtoMessage() {}

func (x *RelatedTopicsIcon) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedTopicsIcon.ProtoReflect.Descriptor instead.
func (*RelatedTopicsIcon) Descriptor() ([]byte, []int) {
	return file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP(), []int{2}
}

func (x *RelatedTopicsIcon) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *RelatedTopicsIcon) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *RelatedTopicsIcon) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

type RelatedTopicsResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstURL string             `protobuf:"bytes,1,opt,name=FirstURL,proto3" json:"FirstURL,omitempty"`
	Icon     *RelatedTopicsIcon `protobuf:"bytes,2,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Result   string             `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result,omitempty"`
	Text     string             `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *RelatedTopicsResults) Reset() {
	*x = RelatedTopicsResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelatedTopicsResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedTopicsResults) ProtoMessage() {}

func (x *RelatedTopicsResults) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedTopicsResults.ProtoReflect.Descriptor instead.
func (*RelatedTopicsResults) Descriptor() ([]byte, []int) {
	return file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP(), []int{3}
}

func (x *RelatedTopicsResults) GetFirstURL() string {
	if x != nil {
		return x.FirstURL
	}
	return ""
}

func (x *RelatedTopicsResults) GetIcon() *RelatedTopicsIcon {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *RelatedTopicsResults) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RelatedTopicsResults) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DuckDuckGoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Abstract         string                  `protobuf:"bytes,1,opt,name=Abstract,proto3" json:"Abstract,omitempty"`
	AbstractSource   string                  `protobuf:"bytes,2,opt,name=AbstractSource,proto3" json:"AbstractSource,omitempty"`
	AbstractText     string                  `protobuf:"bytes,3,opt,name=AbstractText,proto3" json:"AbstractText,omitempty"`
	AbstractURL      string                  `protobuf:"bytes,4,opt,name=AbstractURL,proto3" json:"AbstractURL,omitempty"`
	Answer           string                  `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"`
	AnswerType       string                  `protobuf:"bytes,6,opt,name=AnswerType,proto3" json:"AnswerType,omitempty"`
	Definition       string                  `protobuf:"bytes,7,opt,name=Definition,proto3" json:"Definition,omitempty"`
	DefinitionSource string                  `protobuf:"bytes,8,opt,name=DefinitionSource,proto3" json:"DefinitionSource,omitempty"`
	DefinitionURL    string                  `protobuf:"bytes,9,opt,name=DefinitionURL,proto3" json:"DefinitionURL,omitempty"`
	Heading          string                  `protobuf:"bytes,10,opt,name=Heading,proto3" json:"Heading,omitempty"`
	Image            string                  `protobuf:"bytes,11,opt,name=Image,proto3" json:"Image,omitempty"`
	ImageHeight      int32                   `protobuf:"varint,12,opt,name=ImageHeight,proto3" json:"ImageHeight,omitempty"`
	ImageIsLogo      int32                   `protobuf:"varint,13,opt,name=ImageIsLogo,proto3" json:"ImageIsLogo,omitempty"`
	ImageWidth       int32                   `protobuf:"varint,14,opt,name=ImageWidth,proto3" json:"ImageWidth,omitempty"`
	Redirect         string                  `protobuf:"bytes,15,opt,name=Redirect,proto3" json:"Redirect,omitempty"`
	RelatedTopics    []*RelatedTopicsResults `protobuf:"bytes,16,rep,name=RelatedTopics,proto3" json:"RelatedTopics,omitempty"`
	Results          []*Results              `protobuf:"bytes,17,rep,name=Results,proto3" json:"Results,omitempty"`
	Type             string                  `protobuf:"bytes,18,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *DuckDuckGoResponse) Reset() {
	*x = DuckDuckGoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DuckDuckGoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuckDuckGoResponse) ProtoMessage() {}

func (x *DuckDuckGoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuckDuckGoResponse.ProtoReflect.Descriptor instead.
func (*DuckDuckGoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP(), []int{4}
}

func (x *DuckDuckGoResponse) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *DuckDuckGoResponse) GetAbstractSource() string {
	if x != nil {
		return x.AbstractSource
	}
	return ""
}

func (x *DuckDuckGoResponse) GetAbstractText() string {
	if x != nil {
		return x.AbstractText
	}
	return ""
}

func (x *DuckDuckGoResponse) GetAbstractURL() string {
	if x != nil {
		return x.AbstractURL
	}
	return ""
}

func (x *DuckDuckGoResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *DuckDuckGoResponse) GetAnswerType() string {
	if x != nil {
		return x.AnswerType
	}
	return ""
}

func (x *DuckDuckGoResponse) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *DuckDuckGoResponse) GetDefinitionSource() string {
	if x != nil {
		return x.DefinitionSource
	}
	return ""
}

func (x *DuckDuckGoResponse) GetDefinitionURL() string {
	if x != nil {
		return x.DefinitionURL
	}
	return ""
}

func (x *DuckDuckGoResponse) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *DuckDuckGoResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DuckDuckGoResponse) GetImageHeight() int32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *DuckDuckGoResponse) GetImageIsLogo() int32 {
	if x != nil {
		return x.ImageIsLogo
	}
	return 0
}

func (x *DuckDuckGoResponse) GetImageWidth() int32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *DuckDuckGoResponse) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *DuckDuckGoResponse) GetRelatedTopics() []*RelatedTopicsResults {
	if x != nil {
		return x.RelatedTopics
	}
	return nil
}

func (x *DuckDuckGoResponse) GetResults() []*Results {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DuckDuckGoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type QueryPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer *DuckDuckGoResponse `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
}

func (x *QueryPayload) Reset() {
	*x = QueryPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPayload) ProtoMessage() {}

func (x *QueryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_duckduckgo_typespb_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPayload.ProtoReflect.Descriptor instead.
func (*QueryPayload) Descriptor() ([]byte, []int) {
	return file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP(), []int{5}
}

func (x *QueryPayload) GetAnswer() *DuckDuckGoResponse {
	if x != nil {
		return x.Answer
	}
	return nil
}

var File_pkg_duckduckgo_typespb_types_proto protoreflect.FileDescriptor

var file_pkg_duckduckgo_typespb_types_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75, 0x63, 0x6b, 0x67, 0x6f,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x6f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75, 0x63, 0x6b,
	0x67, 0x6f, 0x22, 0x46, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x22, 0x79, 0x0a, 0x07, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x52,
	0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x52,
	0x4c, 0x12, 0x26, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x67, 0x6f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75, 0x63, 0x6b, 0x67, 0x6f, 0x2e, 0x49,
	0x63, 0x6f, 0x6e, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x22, 0x53, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x12,
	0x33, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x67, 0x6f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75, 0x63, 0x6b, 0x67, 0x6f, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x04,
	0x49, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x22, 0x87, 0x05, 0x0a, 0x12, 0x44, 0x75, 0x63, 0x6b, 0x44, 0x75, 0x63, 0x6b, 0x47, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x62, 0x73, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x62, 0x73, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x41, 0x62, 0x73,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x41,
	0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x55, 0x52,
	0x4c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x48,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x73, 0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x73, 0x4c, 0x6f, 0x67, 0x6f, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x48, 0x0a, 0x0d, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x10, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x6f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75, 0x63, 0x6b, 0x67,
	0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x0d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x6f, 0x64, 0x75, 0x63, 0x6b, 0x64,
	0x75, 0x63, 0x6b, 0x67, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x07, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x48, 0x0a, 0x0c, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x6f, 0x64,
	0x75, 0x63, 0x6b, 0x64, 0x75, 0x63, 0x6b, 0x67, 0x6f, 0x2e, 0x44, 0x75, 0x63, 0x6b, 0x44, 0x75,
	0x63, 0x6b, 0x47, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x6f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75,
	0x63, 0x6b, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x75, 0x63, 0x6b, 0x64, 0x75, 0x63,
	0x6b, 0x67, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_duckduckgo_typespb_types_proto_rawDescOnce sync.Once
	file_pkg_duckduckgo_typespb_types_proto_rawDescData = file_pkg_duckduckgo_typespb_types_proto_rawDesc
)

func file_pkg_duckduckgo_typespb_types_proto_rawDescGZIP() []byte {
	file_pkg_duckduckgo_typespb_types_proto_rawDescOnce.Do(func() {
		file_pkg_duckduckgo_typespb_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_duckduckgo_typespb_types_proto_rawDescData)
	})
	return file_pkg_duckduckgo_typespb_types_proto_rawDescData
}

var file_pkg_duckduckgo_typespb_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_duckduckgo_typespb_types_proto_goTypes = []interface{}{
	(*Icon)(nil),                 // 0: goduckduckgo.Icon
	(*Results)(nil),              // 1: goduckduckgo.Results
	(*RelatedTopicsIcon)(nil),    // 2: goduckduckgo.RelatedTopicsIcon
	(*RelatedTopicsResults)(nil), // 3: goduckduckgo.RelatedTopicsResults
	(*DuckDuckGoResponse)(nil),   // 4: goduckduckgo.DuckDuckGoResponse
	(*QueryPayload)(nil),         // 5: goduckduckgo.QueryPayload
}
var file_pkg_duckduckgo_typespb_types_proto_depIdxs = []int32{
	0, // 0: goduckduckgo.Results.Icon:type_name -> goduckduckgo.Icon
	2, // 1: goduckduckgo.RelatedTopicsResults.Icon:type_name -> goduckduckgo.RelatedTopicsIcon
	3, // 2: goduckduckgo.DuckDuckGoResponse.RelatedTopics:type_name -> goduckduckgo.RelatedTopicsResults
	1, // 3: goduckduckgo.DuckDuckGoResponse.Results:type_name -> goduckduckgo.Results
	4, // 4: goduckduckgo.QueryPayload.Answer:type_name -> goduckduckgo.DuckDuckGoResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_duckduckgo_typespb_types_proto_init() }
func file_pkg_duckduckgo_typespb_types_proto_init() {
	if File_pkg_duckduckgo_typespb_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_duckduckgo_typespb_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Icon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_duckduckgo_typespb_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_duckduckgo_typespb_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelatedTopicsIcon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_duckduckgo_typespb_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelatedTopicsResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_duckduckgo_typespb_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DuckDuckGoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_duckduckgo_typespb_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_duckduckgo_typespb_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_duckduckgo_typespb_types_proto_goTypes,
		DependencyIndexes: file_pkg_duckduckgo_typespb_types_proto_depIdxs,
		MessageInfos:      file_pkg_duckduckgo_typespb_types_proto_msgTypes,
	}.Build()
	File_pkg_duckduckgo_typespb_types_proto = out.File
	file_pkg_duckduckgo_typespb_types_proto_rawDesc = nil
	file_pkg_duckduckgo_typespb_types_proto_goTypes = nil
	file_pkg_duckduckgo_typespb_types_proto_depIdxs = nil
}
